# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

import os
import re
import shutil
import sys
from datetime import datetime

from packaging import version as version_

# Get current location
_DOC_PATH = os.path.dirname(os.path.abspath(__file__))
_PROJ_PATH = os.path.abspath(os.path.join(_DOC_PATH, '..', '..'))
os.chdir(_PROJ_PATH)

# Set environment, remove the pre-installed package
sys.path.insert(0, _PROJ_PATH)
modnames = [mname for mname in sys.modules if mname.startswith('packingsolver3d')]
for modname in modnames:
    del sys.modules[modname]

from packingsolver3d.config.meta import __TITLE__, __AUTHOR__, __VERSION__

project = __TITLE__
copyright = '{year}, {author}'.format(year=datetime.now().year, author=__AUTHOR__)
author = __AUTHOR__

# The short X.Y version
version = version_.parse(__VERSION__).base_version
# The full version, including alpha/beta/rc tags
release = __VERSION__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.todo',
    'sphinx.ext.graphviz',
    'enum_tools.autoenum',
    "sphinx_multiversion",
    'sphinx_toolbox.collapse',
]

mathjax3_config = {
    'tex': {
        'macros': {
            'llbracket': ['\\unicode{x27E6}'],
            'rrbracket': ['\\unicode{x27E7}'],
        },
    },
}

latex_elements = {
    'preamble': r'''
\usepackage{stmaryrd}
''',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#
# ReadTheDocs sets this automatically based on the project's language configuration.
# For local builds, allow override via environment variable.
READTHEDOCS_LANGUAGE = os.environ.get('READTHEDOCS_LANGUAGE', 'en')
language = READTHEDOCS_LANGUAGE
if 'zh' in re.split(r'[_-]+', language.lower()):
    language = 'zh'

_source_index = os.path.join(_DOC_PATH, f'index_{language}.rst')
_target_index = os.path.join(_DOC_PATH, 'index.rst')
if not os.path.exists(_source_index):
    raise FileNotFoundError(f'Source index file not found: {_source_index!r}.')
shutil.copyfile(_source_index, _target_index)

# The master document is now index.rst, which is copied from index_<language>.rst
master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# Locale directories for internationalization
locale_dirs = ['locale/']
gettext_compact = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of plugins themes.
#
html_theme = 'sphinx_rtd_theme'
htmlhelp_basename = 'packingsolver3d'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the plugins static files,
# so a file named "default.css" will overwrite the plugins "default.css".
html_static_path = ['_static']

html_css_files = [
    'css/custom.css',
]

# Language-specific settings
html_context = {
    'display_github': True,
    'github_user': 'hansbug',
    'github_repo': 'packingsolver3d',
    'github_version': 'main',
    'conf_py_path': '/docs/source/',
}

# Add language selector to the theme
if language == 'zh':
    html_context['language'] = 'zh_CN'
    html_context['languages'] = [
        ('English', '../en/'),
        ('中文', '../zh/'),
    ]
else:
    html_context['language'] = 'en'
    html_context['languages'] = [
        ('English', '../en/'),
        ('中文', '../zh/'),
    ]

epub_title = project
epub_exclude_files = ['search.html']

# Whitelist pattern for tags (set to None to ignore all tags)
smv_tag_whitelist = r'^v.*$'  # Include all tags start with 'v'
smv_branch_whitelist = r'^.*$'  # Include all branches
smv_remote_whitelist = r'^.*$'  # Use branches from all remotes
smv_released_pattern = r'^tags/.*$'  # Tags only
smv_outputdir_format = '{ref.name}'  # Use the branch/tag name

if not os.environ.get("ENV_PROD"):
    todo_include_todos = True
    todo_emit_warnings = True
